// Worker entry: OpenNext serves the Next.js app; this adds the queue consumer and cron jobs.
// @ts-expect-error: generated by `opennextjs-cloudflare build`
import handler from '../../.open-next/worker.js';
import type { CfEnv } from '../server/cf';
import type { JobMessage } from '../server/jobs/queue';
import { handleBatch, handleScheduled } from './consumer';

export default {
  fetch: handler.fetch,
  async queue(batch: MessageBatch<JobMessage>, env: CfEnv) {
    await handleBatch(batch, env);
  },
  async scheduled(controller: ScheduledController, env: CfEnv, ctx: ExecutionContext) {
    ctx.waitUntil(handleScheduled(controller, env));
  },
} satisfies ExportedHandler<CfEnv, JobMessage>;

// OpenNext's Durable Objects, re-exported as its docs require for custom workers.
// @ts-expect-error: generated by `opennextjs-cloudflare build`
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from '../../.open-next/worker.js';
